### ISSUE TITLE
MultiQC is very very slow for large projects

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#130]
I believe that the source of this is the picard module, which finds the appropriate log files by searching in (potentially thousands of huge) files, rather than by filename. 

I think that we could change `picard_rnaseq_metrics()` in [functions.sh](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/functions.sh) to write picard data to files with distinctive names (currently they are just `<sample>.txt`), and then change [multiqc_config.yaml](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/multiqc_config.yaml) to look for those particular files, rather than searching within files.

We should also turn off all the parts of the picard output that we're not interested in, as described [here](https://multiqc.info/docs/#optimise-file-search-patterns).

**Comment by hxin** [comment]
Picard module is running slow because a lot [default search pattern](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml) in Picard are using IN FILE SEARCH([contents_re/contents](https://github.com/ewels/MultiQC/blob/master/docs/modules.md)) to identify the Picard log.

What we are currently using is:
```
    picard/rnaseqmetrics:
            contents_re: .*CollectRnaSeqMetrics.*
            shared: true
```
This takes around 3min to finish.

I changed the above to below, but did not seems to make it any faster.
```
    picard/rnaseqmetrics:
            fn: '*.log'
            shared: true
```


Then I disable all the other Picard searches, and it finished in a few seconds.
```
picard/rnaseqmetrics:
            fn: "*.log"
            shared: true
    picard/markdups:
      skip: true
    picard/alignment_metrics:
      skip: true
    picard/basedistributionbycycle:
      skip: true
    picard/gcbias:
      skip: true
    picard/hsmetrics:
      skip: true
    picard/insertsize:
      skip: true
    picard/oxogmetrics:
      skip: true
    picard/pcr_metrics:
      skip: true
    picard/quality_by_cycle:
      skip: true
    picard/quality_score_distribution:
      skip: true
    picard/quality_yield_metrics:
      skip: true
    picard/rrbs_metrics:
      skip: true
    picard/sam_file_validation:
      skip: true
    picard/variant_calling_metrics:
      skip: true
    picard/wgs_metrics:
      skip: true
```
